function M = euler2TranMatrix(thetaX,betaY,gammaZ)
%% rotation sequence is z-> y->x; according the RPY convention
Mx = [1, 0, 0;...
      0,cos(thetaX),-sin(thetaX);...
      0,sin(thetaX),cos(thetaX)];
My = [cos(betaY),0,sin(betaY);...
      0,        1,      0;...
      -sin(betaY),0,cos(betaY)];
Mz = [cos(gammaZ),-sin(gammaZ),0;...
      sin(gammaZ),cos(gammaZ),0;...
      0,           0,        1;];
M = Mz*My*Mx; 

end